mybatis:
    type-aliases-package: com.my61.mybatis.mybatisplus.model
    mapper-locations: 'classpath*:mapper/**Mapper.xml'
    configuration:
        default-fetch-size: 100
        cache-enabled: true
        interceptors:
        map-underscore-to-camel-case: true
        lazy-loading-enabled: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        log-prefix: 'dodo'


spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/test
        username: root
server:
    port: 7777

logging:
    file:
        max-size: 10MB
        max-history: 7
    level:
        root: info



